using System.Runtime.InteropServices;

namespace adblock
{

    static class DnsCache
    {
        [DllImport("dnsapi.dll", EntryPoint = "DnsFlushResolverCache")]
        private static extern uint DnsFlushResolverCache();
        public static uint Flush()
        {
            return DnsFlushResolverCache();
        }
    }


    internal class Program
    {
        const double version = 1.0;
        static void Main()
        {
            try
            {
                string hostsFileName;

                if (!OperatingSystem.IsWindows() || Environment.OSVersion.Version.Major > 10)
                {
                    throw new PlatformNotSupportedException("Detected platform (" + Environment.OSVersion.VersionString + ") is not supported. " + Environment.NewLine +
                        "This program requires Windows 95, 98, ME, or Windows NT 3, 4, 5, 6 and 10");
                }

                string osEnv = string.Empty + Environment.GetEnvironmentVariable("OS");

                if (Environment.OSVersion.Platform != PlatformID.Win32NT)
                {
                    // Operating system is Windows 9x/ME
                    hostsFileName = Environment.GetFolderPath(Environment.SpecialFolder.Windows) + @"\hosts";
                }
                else
                {
                    // Operating system is Windows 3/4/5/6/10
                    hostsFileName = Environment.GetFolderPath(Environment.SpecialFolder.Windows) + @"\System32\drivers\etc\hosts";
                }

                Console.WriteLine("Using file {0}", hostsFileName);

                string programLocation = string.Empty + Path.GetDirectoryName(AppContext.BaseDirectory);
                string backupLocation = programLocation + @"\Backups";
                if (!Directory.Exists(backupLocation))
                {
                    Directory.CreateDirectory(backupLocation);
                }

                Console.WriteLine("Making backups in {0}", backupLocation);

                string backupFileName = string.Empty;

                for (int i = 1; i <= 9999; i++)
                {
                    backupFileName = "hosts" + i.ToString("0000") + ".backup.txt";
                    if (File.Exists(Path.Combine(new string[] { backupLocation, backupFileName })))
                    {
                        //Console.WriteLine("File {0} already exists. ", backupFileName);
                        continue;
                    }
                    else
                    {
                        //Console.WriteLine("File {0} does not exist. ", backupFileName);
                        break;
                    }
                }

                if (string.IsNullOrWhiteSpace(backupFileName))
                {
                    Console.WriteLine("The maximum number of backup files has been created. Please delete old backup files to continue.");
                    Environment.Exit(1);
                }

                backupFileName = Path.Combine(new string[] { backupLocation, backupFileName });
                Console.WriteLine("Using backup file {0}", backupFileName);
                Console.Write("Backing up . . . ");
                File.Copy(hostsFileName, backupFileName);
                Console.WriteLine("Done. ");
                Console.WriteLine();

                const string serverListUrl = "https://raw.githubusercontent.com/anudeepND/blacklist/master/adservers.txt";
                Console.WriteLine("Fetching adserver list . . . ({0})", serverListUrl);
                string serverListWebResult = new HttpClient().GetStringAsync(serverListUrl).Result;
                string serverList = "# generated by adblock by ciao1092, version " + version.ToString("0.0") + Environment.NewLine + "# Ad domain list: " + serverListUrl;

                Console.Write("Processing data . . . ");
                Console.CursorVisible = false;
                string[] serverListWebResultArray = serverListWebResult.ReplaceLineEndings(Environment.NewLine).Split(Environment.NewLine);
                for (int i = 0; i < serverListWebResultArray.Length; i++)
                {
                    string line = serverListWebResultArray[i];
                    if (line.StartsWith("0.0.0.0"))
                    {
                        serverList += Environment.NewLine + line;
                    }

                    int progress = (i + 1) * 100 / serverListWebResultArray.Length;
                    //string progressString = progress.ToString("000") + '%';
                    string progressString = new('#', progress / 10);
                    string toGoString = new('-', 10 - progress / 10);
                    string progressOutput = $"[{progressString}{toGoString}]";
                    Console.Write(progressOutput);
                    Console.CursorLeft -= progressOutput.Length;
                }

                Console.WriteLine();
                Console.CursorVisible = true;

                Console.WriteLine("Making modifications . . . ");
                File.WriteAllText(hostsFileName, serverList);

                Console.WriteLine("Flushing DNS cache . . . ");
                DnsCache.Flush();

                Console.WriteLine("You may need to reboot your PC for the changes to take effect. ");

                Console.WriteLine();
                Console.ForegroundColor = ConsoleColor.Green;
                Console.WriteLine("All done!");
                Console.ResetColor();
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message.ToString());
                Environment.Exit(1);
                return;
            }
        }
    }
}
